= Outros Recursos

== Date Picker

Recurso que permite manipular dados do calendário.

Para mais detalhes: GOOGLE DEVELOPERS. DatePicker. Disponível em: https://developer.android.com/reference/android/widget/DatePicker. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:um/activity_main.xml[activity_main]

- link:um/MainActivity.java[MainActivity]

== Date Picker Dialog

Recurso que permite manipular dados do calendário.

Para mais detalhes: GOOGLE DEVELOPERS. DatePickerDialog. Disponível em: https://developer.android.com/reference/android/widget/DatePickerDialog. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:dois/activity_main.xml[activity_main]

- link:dois/MainActivity.java[MainActivity]

== Time Picker

Recurso que permite manipular dados das horas.

Para mais detalhes: GOOGLE DEVELOPERS. TimePicker. Disponível em: https://developer.android.com/reference/android/widget/TimePicker. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:tres/activity_main.xml[activity_main]

- link:tres/MainActivity.java[MainActivity]

== Time Picker Dialog

Recurso que permite manipular dados das horas.

Para mais detalhes: GOOGLE DEVELOPERS. TimePickerDialog. Disponível em: https://developer.android.com/reference/android/widget/TimePickerDialog. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:quatro/activity_main.xml[activity_main]

- link:quatro/MainActivity.java[MainActivity]

