= Content Provider

Recurso que possibilita compartilhar dados privados entre aplicativos. 

Para mais detalhes: GOOGLE DEVELOPERS. Fundamentos do provedor de conteúdo. Disponível em: 
https://developer.android.com/guide/topics/providers/content-provider-basics?hl=pt-br. Acesso em: 24 fev. 2023.

Content Provider

video::fNVMqACYPnQ[youtube, width=640, height=480]

Exemplos práticos (Baseado em: Stack overflow. Android: não estou obtendo nenhum contato da lista de contatos. 2018. Disponível em: 
https://stackoverflow.com/questions/53956496/android-not-getting-any-contacts-from-contact-list. Pergunta feita pelo usuário 
https://stackoverflow.com/users/4951663/mohit-suthar e respondida pelo https://stackoverflow.com/users/4390987/%e0%a5%90-rakesh-kumar.):

- Contato.java
[source,java]
public class Contato {
   private int id;
   private String nome, fone;
   public Contato(int id, String nome, String fone) {
       this.id = id;
       this.nome = nome;
       this.fone = fone;
   }
   public int getId() {
       return id;
   }
   public void setId(int id) {
       this.id = id;
   }
   public String getNome() {
       return nome;
   }
   public void setNome(String nome) {
       this.nome = nome;
   }
   public String getFone() {
       return fone;
   }
   public void setFone(String fone) {
       this.fone = fone;
   }
   @Override
   public String toString() {
       return "Contato{" +
               "id=" + id +
               ", nome='" + nome + '\'' +
               ", fone='" + fone + '\'' +
               '}';
   }
}

- MainActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.Manifest;
import android.content.ContentResolver;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.ContactsContract;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;
import java.util.ArrayList;
public class MainActivity extends AppCompatActivity implements
       AdapterView.OnItemClickListener {
   private ListView lista;
   private ArrayAdapter<Contato> dadosAdapter;
   private static final int PERMISSIONS_REQUEST_READ_CONTACTS = 100;
   @Override
   protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
       setContentView(R.layout.activity_main);
       lista = findViewById(R.id.lista);
       dadosAdapter = new ArrayAdapter<>(getApplicationContext(),
               android.R.layout.simple_list_item_1, obterDados());
       lista.setAdapter(dadosAdapter);
       lista.setOnItemClickListener(this);
   }
   public ArrayList<Contato> obterDados(){
       String projection[] = null;
       String select = null;
       String selectArgs[] = null;
       String sortOrder = null;
       Uri uri = null;
       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M
               && checkSelfPermission(Manifest.permission.READ_CONTACTS)
               != PackageManager.PERMISSION_GRANTED) {
           requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},
                   PERMISSIONS_REQUEST_READ_CONTACTS);
           uri = ContactsContract.CommonDataKinds.Contactables.CONTENT_URI;
       } else {
           uri = ContactsContract.Data.CONTENT_URI;
       }
       ContentResolver contentResolver = getContentResolver();
       Cursor cursor = contentResolver.query(uri, projection, select, selectArgs,
               sortOrder);
       ArrayList<Contato> dados = new ArrayList<>();
       while (cursor.moveToNext()){
           int id = cursor.getInt(cursor.
                   getColumnIndex(ContactsContract.Data.CONTACT_ID));
           String nome = cursor.getString(cursor.getColumnIndex(
                   ContactsContract.Contacts.DISPLAY_NAME));
           String data = cursor.getString(cursor.getColumnIndex(
                   ContactsContract.CommonDataKinds.Contactables.DATA));
           dados.add(new Contato((int) id, nome, data));
       }
       return dados;
   }
   @Override
   public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
       Contato item = (Contato) parent.getItemAtPosition(position);
       Toast.makeText(MainActivity.this, item.toString(),
               Toast.LENGTH_SHORT).show();
   }
}

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:layout_margin="10dp"
    tools:context=".MainActivity">
    <ListView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/lista"/>
</LinearLayout>

- No arquivo AndroidManifest.xml, deve-se acrescentar a tag <uses-permission android:name="android.permission.READ_CONTACTS" />

Exemplos práticos (criar um provedor de conteúdo em seu app):

- DadosProvider.java
[source,java]
import android.content.ContentProvider;
import android.content.ContentUris;
import android.content.ContentValues;
import android.content.Context;
import android.content.UriMatcher;
import android.database.Cursor;
import android.database.SQLException;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.database.sqlite.SQLiteQueryBuilder;
import android.net.Uri;
import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
public class DadosProvider extends ContentProvider {
   private static final int BANCO_VERSAO = 1;
   private static final String BANCO_NOME = "meu_banco";
   private static final String BANCO_TABELA = "contato";
   private static final String ID = "_id";
   private static final String NOME = "nome";
   private static final String TELEFONE = "telefone";
   private static final String CRIA_TABELA =
           "CREATE TABLE "+BANCO_TABELA +
                   "("+ID +" INTEGER PRIMARY KEY AUTOINCREMENT, " +
                   NOME+" TEXT, "+TELEFONE+" TEXT"+")";
   private static final String DELETA_TABELA = "DROP TABLE IF EXISTS "+
           BANCO_TABELA;
   private SQLiteDatabase banco;
   private static final String TAG = DadosProvider.class.getName();
   private static final String NOME_PROVIDER="com.example.appbancosqlite.DadosProvider"; //definição da autoridade (nome simbólico)
   private static final String URL = "content://"+NOME_PROVIDER+"/dados"; // definição da autoridade e da tabela a ser acessada
   private static final Uri URI_CONTEUDO = Uri.parse(URL); // converte a String em uma URI
   private static final int CODIGO_URI_TODOS = 1;
   private static final UriMatcher URI_MATCHER;
   static
   {
       //Classe de utilitária para auxiliar na correspondência de URIs em provedores de conteúdo.
       URI_MATCHER = new UriMatcher(UriMatcher.NO_MATCH);
       // acessa todos os registros da tabela
       URI_MATCHER.addURI(NOME_PROVIDER, "dados/", CODIGO_URI_TODOS);
   }
  @Override
   public boolean onCreate()  // acessa o banco de dados no modo escrita
   {
       Context context = getContext();
       BancoHelper helper = new BancoHelper(context);
       banco = helper.getWritableDatabase();
       if(banco!=null){
           Log.i(TAG,"provedor criado");
           return true;
       }
       return false;
   }//onCreate
   @Nullable
   @Override
   public Cursor query(Uri uri, String[] projection, String selection,
                       String[] selectionArgs, String sortOrder)
   {
       SQLiteQueryBuilder sqb = new SQLiteQueryBuilder();
       sqb.setTables(BANCO_TABELA);
       Cursor cursor =  sqb.query(banco,projection,selection,selectionArgs
               ,null,null,null);   //obtém os dados da tabela e devolve em um Cursor
       cursor.setNotificationUri(getContext().getContentResolver(), uri); //para notificar as alterações.
       Log.i(TAG,"obtém dados");
       return cursor;
   }
   @Override
   public String getType(Uri uri) //defini o MIME TYPE
   {
       switch (URI_MATCHER.match(uri))
       {
           case CODIGO_URI_TODOS:
               return "vnd.android.cursor.dir/dados";
           default:
               throw new IllegalArgumentException("ERROR uri: " + uri);
       }
   }//getType
   @Nullable
   @Override
   public Uri insert(@NonNull Uri uri, @Nullable ContentValues contentValues) {
       long id = banco.insert(BANCO_TABELA,null,contentValues); //inseri os dados na tabela
       if (id >0)
       {
           Uri uriID = ContentUris.withAppendedId(URI_CONTEUDO,id); //obtém a URI com o ID retornado
           getContext().getContentResolver().notifyChange(uriID, null); //Notifique os observadores registrados que uma linha foi atualizada e tente sincronizar as alterações na rede.
           Log.i(TAG,"dados inseridos");
           return uriID;
       }
       throw new SQLException("ERROR: insert ");
   }//insert
   @Override
   public int delete(@NonNull Uri uri, @Nullable String selection, @Nullable String[] selectionArgs) {
       int count=0;
       switch (URI_MATCHER.match(uri))
       {
           case CODIGO_URI_TODOS:
               count = banco.delete(BANCO_TABELA, selection, selectionArgs); //deleta os dados da tabela
               Log.i(TAG,"dados deletados");
               break;
           default:
               throw new IllegalArgumentException
                   ("ERROR: delete ");
       }
       getContext().getContentResolver().notifyChange(uri, null);
       return count;
   }
   @Override
   public int update(@NonNull Uri uri, @Nullable ContentValues contentValues,
                     @Nullable String selection, @Nullable String[] selectionArgs) {
       int count = 0;
       switch (URI_MATCHER.match(uri))
       {
           case CODIGO_URI_TODOS:
               count =  banco.update   //altera os dados da tabela
                       (BANCO_TABELA,contentValues,selection,selectionArgs);
               Log.i(TAG,"dados alterados");
               break;
           default:
               throw new IllegalArgumentException
                   ("ERROR: update" );
       }
       getContext().getContentResolver().notifyChange(uri, null);
       return count;
   }
   private static class BancoHelper extends SQLiteOpenHelper
   {
       BancoHelper(Context context)
       {
           super(context, BANCO_NOME, null, BANCO_VERSAO);
       }
       @Override
       public void onCreate(SQLiteDatabase sqLiteDatabase)
       {
           sqLiteDatabase.execSQL(CRIA_TABELA);
       }
       @Override
       public void onUpgrade(SQLiteDatabase sqLiteDatabase, int oldVersion,
                             int newVersion)
       {
           sqLiteDatabase.execSQL(DELETA_TABELA);
           onCreate(sqLiteDatabase);
       }
   }//inner class
}//class

