= Outros Recursos

== Date Picker

Recurso que permite manipular dados do calendário.

Para mais detalhes: GOOGLE DEVELOPERS. DatePicker. Disponível em: https://developer.android.com/reference/android/widget/DatePicker. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:um/activity_main.xml[activity_main]

- link:um/MainActivity.java[MainActivity]

== Date Picker Dialog

Recurso que permite manipular dados do calendário.

Para mais detalhes: GOOGLE DEVELOPERS. DatePickerDialog. Disponível em: https://developer.android.com/reference/android/widget/DatePickerDialog. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:dois/activity_main.xml[activity_main]

- link:dois/MainActivity.java[MainActivity]

== Time Picker

Recurso que permite manipular dados das horas.

Para mais detalhes: GOOGLE DEVELOPERS. TimePicker. Disponível em: https://developer.android.com/reference/android/widget/TimePicker. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:tres/activity_main.xml[activity_main]

- link:tres/MainActivity.java[MainActivity]

== Time Picker Dialog

Recurso que permite manipular dados das horas.

Para mais detalhes: GOOGLE DEVELOPERS. TimePickerDialog. Disponível em: https://developer.android.com/reference/android/widget/TimePickerDialog. Acesso em: 24 fev. 2023.

Exemplos práticos:

- link:quatro/activity_main.xml[activity_main]

- link:quatro/MainActivity.java[MainActivity]

== SMS

Recurso que permite acessar o aplicativo de SMS que já vem instalado no dispositivo móvel.

Exemplos práticos (Baseado no conteúdo: How to get the package name of sms app(default) in Android before KitKat version? Disponível em: <https://stackoverflow.com/questions/29471386/how-to-get-the-package-name-of-sms-appdefault-in-android-before-kitkat-version?noredirect=1&lq=1&gt;. Pergunta realizada pelo usuário: https://stackoverflow.com/users/3986081/malleswar-chinta e respondida pelo usuário: https://stackoverflow.com/users/3020568/deniz.):

- link:cinco/activity_main.xml[activity_main]

- link:cinco/MainActivity.java[MainActivity]

== WhatsApp

Recurso que permite acessar o aplicativo WhatsApp instalado no dispositivo móvel.

Exemplos práticos(Baseado no conteúdo: https://faq.whatsapp.com/android/im-an-android-developer-how-can-i-integrate-whatsapp-with-my-app/?lang=en):

- link:seis/activity_main.xml[activity_main]

- link:seis/MainActivity.java[MainActivity]

== Gmail

Recurso que permite acessar o aplicativo Gmail instalado no dispositivo móvel.

Exemplos práticos:

- link:sete/activity_main.xml[activity_main]

- link:sete/MainActivity.java[MainActivity]

== Video View

Recurso que oferece controle de vídeo como: play, pause e stop.

Para mais detalhes: GOOGLE DEVELOPERS. VideoView. Disponível em: https://developer.android.com/reference/android/widget/VideoView. Acesso em: 24 fev. 2023.

== Text To Speech

Recurso que converte o texto disponível em seu app em voz.

Para mais detalhes: GOOGLE DEVELOPERS. TextToSpeech. Disponível em: https://developer.android.com/reference/android/speech/tts/TextToSpeech e 
ANDROID DEVELOPERS BLOG. An introduction to Text-To-Speech in Android. Disponível em: https://android-developers.googleblog.com/2009/09/introduction-to-text-to-speech-in.html.

Exemplos práticos(Exemplo adaptado das seguintes fontes: Text to speech (TTS) - Android. Disponível em:<https://stackoverflow.com/questions/3058919/text-to-speechtts-android, pergunta realizada pelo usuário https://stackoverflow.com/users/366916/bharathi e respondida pelo usuário https://stackoverflow.com/users/3166375/sifat-ifty.
Playing a video in VideoView in Anroid. Disponível em:<https://stackoverflow.com/questions/3263736/playing-a-video-in-videoview-in-android&gt;, pergunta realizada pelo usuário https://stackoverflow.com/users/2355649/muhammad-maqsoodur-rehman e respondida pelo usuário https://stackoverflow.com/users/3681880/suragch.):

- link:oito/activity_main.xml[activity_main]

- link:oito/MainActivity.java[MainActivity]

- link:oito/activity_segunda.xml[activity_segunda]

- link:oito/SegundaActivity.java[SegundaActivity]

- criar uma pasta chamada raw no projeto, o vídeo deve estar armazenado dentro desta pasta.

== Android Accessibility Suite / Android Studio Profiles / Novidades

Video::[]







