= Content Provider

Recurso que possibilita compartilhar dados privados entre aplicativos. 

Para mais detalhes: GOOGLE DEVELOPERS. Fundamentos do provedor de conteúdo. Disponível em: 
https://developer.android.com/guide/topics/providers/content-provider-basics?hl=pt-br. Acesso em: 01 set. 2025.

Content Provider

video::fNVMqACYPnQ[youtube, width=640, height=480]

Exemplo 01: (Adaptado de: Stack overflow. Android: não estou obtendo nenhum contato da lista de contatos. 2018. Disponível em: 
https://stackoverflow.com/questions/53956496/android-not-getting-any-contacts-from-contact-list. Pergunta feita pelo usuário 
https://stackoverflow.com/users/4951663/mohit-suthar e respondida pelo https://stackoverflow.com/users/4390987/%e0%a5%90-rakesh-kumar.):

- No arquivo AndroidManifest.xml, deve-se acrescentar a tag <uses-permission android:name="android.permission.READ_CONTACTS" />

- Contato.java
[source,java]
public class Contato {
   private int id;
   private String nome, fone;
   public Contato(int id, String nome, String fone) {
       this.id = id;
       this.nome = nome;
       this.fone = fone;
   }
   public int getId() {
       return id;
   }
   public void setId(int id) {
       this.id = id;
   }
   public String getNome() {
       return nome;
   }
   public void setNome(String nome) {
       this.nome = nome;
   }
   public String getFone() {
       return fone;
   }
   public void setFone(String fone) {
       this.fone = fone;
   }
   @Override
   public String toString() {
       return "Contato{" +
               "id=" + id +
               ", nome='" + nome + '\'' +
               ", fone='" + fone + '\'' +
               '}';
   }
}

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:layout_margin="10dp"
    tools:context=".MainActivity">
    <ListView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/lista"/>
</LinearLayout>

- MainActivity.java
[source,java]
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import android.Manifest;
import android.content.ContentResolver;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.ContactsContract;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;
import java.util.ArrayList;
public class MainActivity extends AppCompatActivity
        implements AdapterView.OnItemClickListener {
    private ListView lista;
    private ArrayAdapter<Contato> dadosAdapter;
    private static final int PERMISSIONS_REQUEST_READ_CONTACTS = 100;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        lista = findViewById(R.id.lista);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M &&
                checkSelfPermission(Manifest.permission.READ_CONTACTS)
                        != PackageManager.PERMISSION_GRANTED) {
            requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},
                    PERMISSIONS_REQUEST_READ_CONTACTS);
        } else {
            carregarContatos();
        }
    }
    private void carregarContatos() {
        ArrayList<Contato> contatos = obterDados();
        dadosAdapter = new ArrayAdapter<>(MainActivity.this,
                android.R.layout.simple_list_item_1, contatos);
        lista.setAdapter(dadosAdapter);
        lista.setOnItemClickListener(this);
    }
    public ArrayList<Contato> obterDados() {
        ArrayList<Contato> dados = new ArrayList<>();
        Uri uri = ContactsContract.CommonDataKinds.Phone.CONTENT_URI;
        String[] projection = {
                ContactsContract.CommonDataKinds.Phone.CONTACT_ID,
                ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,
                ContactsContract.CommonDataKinds.Phone.NUMBER
        };
        ContentResolver resolver = getContentResolver();
        Cursor cursor = resolver.query(uri, projection, null, null,
                ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME + " ASC");
        if (cursor != null) {
            int idIndex = cursor.getColumnIndex(ContactsContract.CommonDataKinds.Phone.CONTACT_ID);
            int nameIndex = cursor.getColumnIndex(ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME);
            int phoneIndex = cursor.getColumnIndex(ContactsContract.CommonDataKinds.Phone.NUMBER);
            while (cursor.moveToNext()) {
                int id = cursor.getInt(idIndex);
                String nome = cursor.getString(nameIndex);
                String fone = cursor.getString(phoneIndex);
                dados.add(new Contato(id, nome, fone));
            }
            cursor.close();
        }
        return dados;
    }
    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Contato item = (Contato) parent.getItemAtPosition(position);
        Toast.makeText(MainActivity.this, item.toString(), Toast.LENGTH_SHORT).show();
    }
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == PERMISSIONS_REQUEST_READ_CONTACTS) {
            if (grantResults.length > 0 &&
                    grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                carregarContatos();
            } else {
                Toast.makeText(this, "Permissão negada!!!!", Toast.LENGTH_SHORT).show();
            }
        }
    }
}

Exemplo 02: (criar um provedor de conteúdo em seu app)

