= Broadcast Receiver

Segundo a Google Developers (2019), "Os apps para Android podem enviar ou receber mensagens de transmissão do sistema Android e de outros apps Android". 
Para entender com mais facilidade os broadcasts, relembre os tratamentos de eventos presentes na linguagem Java. Evento é algo que acontece no sistema:
pode ser sua reinicialização; o aparelho habilitado em modo avião; a bateria sendo carregada, a desabilitação da Wi-fi e assim por diante.
Resumindo: algo acontece, uma classe transmite uma mensagem e outra ficará responsável em tratá-la.

Ainda, de acordo com a  Google Developers (2019), "Os apps podem se registrar para receber transmissões específicas. Quando uma transmissão é enviada,
o sistema a direciona automaticamente para apps que se inscreveram para receber esse tipo específico de transmissão."

Para ocorrer a transmissão da mensagem, é necessário vinculá-la ao um objeto Intent. Através do método setAction é definido o evento que aconteceu. 
Por meio do método putExtra é possível passar mais dados na transmissão da mensagem.

- Referência do texto entre aspas: GOOGLE DEVELOPERS. Visão geral de transmissões.Disponível em: 
https://developer.android.com/guide/components/broadcasts#java. Acesso em: 22 de fev. 2023. 

Broadcast Receiver

video::XXVsL3njoCQ[youtube, width=640, height=480]

Existem duas maneiras de definir um BroadcastReceiver:

- No arquivo AndroidManifest.xml;

- Pelo contexto, cuja definição é feita por linha de código dentro de uma classe específica.

Para saber mais sobre as ações de transmissões existentes no Android, acesse na sua máquina a pasta do SDK. Por exemplo, na minha máquina o acesso ao 
arquivo foi: Sdk/platforms/android-31/data/broadcast_actions.txt. 

Exemplos práticos:

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">
   <Button
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:id="@+id/buttonGerar"
       android:text="Gerar" />
    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/buttonDisparar"
        android:text="Disparar" />
    <ListView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/listViewNumeros"/>

</LinearLayout>

- MainActivity.java
[source,java]
public class MainActivity extends AppCompatActivity {
    private Button buttonGerar, buttonDisparar;
    private ListView listViewNumeros;
    private ArrayAdapter<Integer> adapter;
    private ArrayList<Integer> dados;
    private int numeroAleatorio;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        buttonGerar = findViewById(R.id.buttonGerar);
        buttonDisparar = findViewById(R.id.buttonDisparar);
        listViewNumeros = findViewById(R.id.listViewNumeros);
        dados = new ArrayList<>();
        adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, dados);
        listViewNumeros.setAdapter(adapter);
        MyBroadcastReceiver myBroadcastReceiver = new MyBroadcastReceiver(); //objeto da classe
        IntentFilter intentFilter = new IntentFilter();  //cria uma IntentFilter 
        intentFilter.addAction("com.example.appmybroadcastreceiver.MY_INTENT"); // defini as ações de transmissão. 
        registerReceiver(myBroadcastReceiver, intentFilter); //registra a classe que irá receber a mensagem do transmissor específico.
    }//onCreate
    public void clicar(View v) {
        switch (v.getId()) {
            case R.id.buttonGerar:
                Random random = new Random();
                numeroAleatorio = random.nextInt(10);
                Toast.makeText(this, "número gerado", Toast.LENGTH_SHORT).show();
                break;
            case R.id.buttonDisparar:
                dispararEvento();
                break;
        }//switch
    }//clicar
    private void dispararEvento() {
        Intent intent = new Intent();  //cria-se uma Intent
        intent.putExtra("numero", numeroAleatorio);  //adiciona-se a informação a ser passada
        intent.setAction("com.example.appmybroadcastreceiver.MY_INTENT"); //especifica-se o destinatário que recebe este dado extra
        sendBroadcast(intent); //envia a mensagem
    }//
    private class MyBroadcastReceiver extends BroadcastReceiver { //para tratar a mensagem, é necessário estender a classe BroadcastReceiver, pois assim, terá acesso ao método onReceive.
        @Override
        public void onReceive(Context context, Intent intent) {  //método capaz de tratar a mensagem disparada
            int num = intent.getIntExtra("numero", 0);  //obter o dado extra vindo da Intent
            dados.add(num); //adiciona o número no ArrayList
            adapter.notifyDataSetChanged();   //altera o adapter que preenche a ListView
        }//
    }//inner class
}//class

Exemplos práticos:

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:id="@+id/textViewHello"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>

- MainActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}

- activity_2.xml
[source,xml] 
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".Activity2">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Segunda activity"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>

- Activity2.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
public class Activity2 extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_2);
    }
}

- MyBroadcast.java
[source,java]
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.widget.Toast;
public class MyBroadcast extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
        if(intent.getAction() == "android.intent.action.AIRPLANE_MODE"){  //verifica se a transmissão foi realizada por habilitar o modo avião do aparelho
            Intent i = new Intent(context,Activity2.class); //criar uma Intent, pois o objeto é quando o celular for colocado em modo avião, invoque a segunda tela.
            i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);  //a tela a ser mostrada será iniciada em uma nova pilha
            context.startActivity(i); //inicia a segunda tela
        }
    }
}

- AndroidManifest.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <application
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.AppBroadcast2603_02"
        tools:targetApi="31">
        <activity
            android:name=".Activity2"
            android:exported="false">
            <meta-data
                android:name="android.app.lib_name"
                android:value="" />
        </activity>
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data
                android:name="android.app.lib_name"
                android:value="" />
        </activity>
        <receiver android:name=".MyBroadcast" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.AIRPLANE_MODE" />
            </intent-filter>
        </receiver>
    </application>

Atenção: No exemplo 1, como foi uma transmissão de uma ação personalizada, a configuração foi feita de forma programática (dentro da classe MainActivity). No exemplo 2, a definição foi feita no arquivo.xml.



