= Alarm Manager

Uma opção para efetuar operações baseadas em tempo.

Para mais detalhes: GOOGLE DEVELOPERS. Disponível em: https://developer.android.com/training/scheduling/alarms?hl=pt-br#java. Acesso em: 23 fev. 2023.

Exemplos práticos:

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   tools:context=".MainActivity">
   <TextView
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:text="Hello World!"
       app:layout_constraintBottom_toBottomOf="parent"
       app:layout_constraintLeft_toLeftOf="parent"
       app:layout_constraintRight_toRightOf="parent"
       app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>

- MainActivity.java
[source,java]
public class MainActivity extends AppCompatActivity {
    private AlarmManager alarmManager;
    private PendingIntent pendingIntent;
    @Override
    protected void onStart() {
        super.onStart();
        disparar();
    }
    private void disparar() {
        alarmManager = (AlarmManager) getSystemService(ALARM_SERVICE);
        Intent i = new Intent(this, MyBroadcast.class);
        pendingIntent = PendingIntent.getBroadcast(this, 0, i, 0);
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(System.currentTimeMillis());
        calendar.set(Calendar.HOUR_OF_DAY, 18);
        calendar.set(Calendar.MINUTE, 42);
        alarmManager.set(AlarmManager.RTC_WAKEUP,calendar.getTimeInMillis() + 2 * 1000,pendingIntent);
    }//
}

- MyBroadcastReceiver.java
[source,java]
public class MyBroadcastReceiver extends BroadcastReceiver {
   @Override
   public void onReceive(Context context, Intent intent) {
       Toast.makeText(context,"hora de estudar",Toast.LENGTH_SHORT).show();
   }
}

- No arquivo AndroidManifest.xml, deve-se acrescentar a tag <receiver android:name=".MyBroadcastReceiver"/>

O objetivo do método disparar é criar um AlarmManager no qual dispara um BroadcastReceiver depois de um determinado tempo definido.

Para que o alarme repita em dois em dois minutos, basta trocar o método alarmManager.set() para alarmManager.setRepeating(). 

Veja o exemplo:

alarmManager.setRepeating(AlarmManager.RTC_WAKEUP, calendar.getTimeInMillis(),1000 * 2, pendingIntent);

Exemplos práticos:

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   tools:context=".MainActivity">
   <TextView
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:text="Hello World!"
       android:id="@+id/textHello"
       android:onClick="disparar"
       app:layout_constraintBottom_toBottomOf="parent"
       app:layout_constraintLeft_toLeftOf="parent"
       app:layout_constraintRight_toRightOf="parent"
       app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>

- MainActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.app.AlarmManager;
import android.app.PendingIntent;
import android.content.Intent;
import android.os.Bundle;
import android.os.SystemClock;
import android.view.View;
import android.widget.Toast;
import java.util.Calendar;
import java.util.Random;
public class MainActivity extends AppCompatActivity {
   private AlarmManager alarmManager;
   private PendingIntent pendingIntent;
   private Integer numeroGerado;
   @Override
   protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
       setContentView(R.layout.activity_main);
       numeroGerado = gerarNumero();
       Toast.makeText(this, numeroGerado.toString(),Toast.LENGTH_SHORT).show();
   }
   private int gerarNumero(){
       Random random = new Random();
       int numeroAleatorio = random.nextInt(10);
       return numeroAleatorio;
   }
   public void disparar(View view) {
       if(view.getId() == R.id.textHello){
           Toast.makeText(this, "clicado", Toast.LENGTH_SHORT).show();
           alarmManager = (AlarmManager) getSystemService(ALARM_SERVICE);
           Intent i = new Intent(this, MyBroadcast.class);
           i.putExtra("numeroGerado",numeroGerado);
           pendingIntent = PendingIntent.getBroadcast(this,0,i,0);
           /*Calendar calendar = Calendar.getInstance();
           calendar.setTimeInMillis(System.currentTimeMillis());
           calendar.set(Calendar.HOUR_OF_DAY,18);
           calendar.set(Calendar.MINUTE,16);*/
           alarmManager.set(AlarmManager.ELAPSED_REALTIME_WAKEUP,
                   SystemClock.elapsedRealtime() +
                           60 * 1000, pendingIntent);
       }
   }
}

- MyBroadcastReceiver.java
[source,java]
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.widget.Toast;
public class MyBroadcastReceiver extends BroadcastReceiver {
   @Override
   public void onReceive(Context context, Intent intent) {
       Integer num = intent.getIntExtra("numeroGerado",0);
       Toast.makeText(context,"número gerado: "+num.toString(),Toast.LENGTH_SHORT).show();
   }
}

- No arquivo AndroidManifest.xml, deve-se acrescentar a tag <receiver android:name=".MyBroadcastReceiver"/>
