== Calculadora MVVM

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
    <data>
        <variable
            name="vm"
            type="com.ktl.mvvm_calculadoraimc.CalculadoraIMCViewModel" />
    </data>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:padding="16dp">
        <EditText
            android:id="@+id/editTextPeso"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:autofillHints=""
            android:hint="@string/digite_seu_peso"
            android:inputType="numberDecimal" />
        <EditText
            android:id="@+id/editTextAltura"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:autofillHints=""
            android:hint="@string/digite_sua_altura"
            android:inputType="numberDecimal" />
        <Button
            android:id="@+id/buttonCalcular"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/calcular" />
        <TextView
            android:id="@+id/textViewResultado"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@{vm.tipo}" />
        <TextView
            android:id="@+id/textViewResultadoNumero"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@{vm.resultado}" />
    </LinearLayout>
</layout>

- CalculadoraIMC.java
[source,java]
public class CalculadoraIMC {
    public static double calcular(double peso, double altura) {
        return peso / (altura * altura);
    }
    public static String getTipo(double imc) {
        if (imc < 18.5) {
            return "Abaixo do peso";
        } else if (imc <= 24.9) {
            return "Peso normal";
        } else if (imc <= 29.9) {
            return "Sobrepeso";
        } else if (imc <= 34.9) {
            return "Obesidade Grau I";
        } else if (imc <= 39.9) {
            return "Obesidade Grau II";
        } else {
            return "Obesidade Grau III (mórbida)";
        }
    }
}

- CalculadoraIMCViewModel.java
[source,java]
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;
public class CalculadoraIMCViewModel extends ViewModel {
    private final MutableLiveData<String> resultado;
    private final MutableLiveData<String> tipo;
    public CalculadoraIMCViewModel() {
        this.tipo = new MutableLiveData<>();
        resultado = new MutableLiveData<>();
    }
    public MutableLiveData<String> getResultado() {
        return resultado;
    }
    public MutableLiveData<String> getTipo() {
        return tipo;
    }
    public void calcular(double peso, double altura) {
        double imc = CalculadoraIMC.calcular(peso, altura);
        resultado.setValue(String.valueOf(imc));
        tipo.setValue(CalculadoraIMC.getTipo(imc));
    }
}

- MainActivity.java
[source,java]
import android.os.Bundle;
import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.databinding.DataBindingUtil;
import androidx.lifecycle.ViewModelProvider;
import com.ktl.mvvm_calculadoraimc.databinding.ActivityMainBinding;
public class MainActivity extends AppCompatActivity {
    private CalculadoraIMCViewModel vm;
    private ActivityMainBinding binding;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main);
        vm = new ViewModelProvider(this).get(CalculadoraIMCViewModel.class);
        binding.setVm(vm);
        binding.setLifecycleOwner(this);
        binding.buttonCalcular.setOnClickListener(v -> {
            double peso = Double.parseDouble(binding.editTextPeso.getText().toString());
            double altura = Double.parseDouble(binding.editTextAltura.getText().toString());
            vm.calcular(peso, altura);
        });
    }
}

== App GsonHttp com MVVM e DataBinding

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:padding="10dp"
        tools:context=".view.MainActivity">
        <Button
            android:id="@+id/btObterDados"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            android:gravity="center"
            android:text="@string/obter_dados" />
        <ListView
            android:id="@+id/listViewDados"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:divider="@android:color/darker_gray"
            android:dividerHeight="1dp" />
    </LinearLayout>
</layout>

- item_contato.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
    <data>
        <variable
            name="contato"
            type="com.example.appgsonhttp_01.model.InformacoesContato" />
    </data>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:padding="16dp">
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@{contato.nome}"
            android:textColor="@android:color/black"
            android:textSize="18sp"
            android:textStyle="bold" />
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@{contato.telefone}"
            android:textSize="14sp" />
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@{contato.email}"
            android:textSize="14sp" />
    </LinearLayout>
</layout>

- activity_relatorio.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
    <data>
        <variable
            name="viewModel"
            type="com.example.appgsonhttp_01.viewmodel.RelatorioViewModel" />
    </data>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:layout_marginTop="30dp"
        android:padding="16dp">
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text='@{"Nome: " + viewModel.nome_professor}'
            android:textSize="20sp"
            android:textStyle="bold" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text='@{"Email: " + viewModel.email_professor}'
            android:textSize="18sp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text='@{"Telefone: " + viewModel.telefone_professor}'
            android:textSize="18sp"
            android:layout_marginBottom="12dp" />
    </LinearLayout>
</layout>

- Conexao.java
[source,java]
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
public class Conexao {
    public InputStream obterRespostaHTTP(String endURL) {
        HttpURLConnection conexao = null;
        try {
            URL url = new URL(endURL);
            conexao = (HttpURLConnection) url.openConnection();
            conexao.setConnectTimeout(50000);
            conexao.setReadTimeout(50000);
            conexao.setRequestMethod("GET");
            conexao.connect();
            return new BufferedInputStream(conexao.getInputStream());/// n esqueça
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }//
}

- Conversao.java
[source,java]
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
public class Conversao {
    public String converter(InputStream inputStream) {
        if(inputStream == null){
            return null;
        }
        InputStreamReader inputStreamReader = new InputStreamReader(inputStream);
        BufferedReader br = new BufferedReader(inputStreamReader);
        StringBuilder stringBuilder = new StringBuilder();
        String conteudo;
        try{
            while((conteudo = br.readLine())!= null){
                stringBuilder.append(conteudo).append("\n");
            }
        }catch (IOException e){
            e.printStackTrace();
        }
        return stringBuilder.toString();
    }
}

- Adicionais.java
[source,java]
import javax.annotation.processing.Generated;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
@Generated("jsonschema2pojo")
public class Adicionais {
    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("email")
    @Expose
    private String email;
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
}

- Agenda.java
[source,java]
import javax.annotation.processing.Generated;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
@Generated("jsonschema2pojo")
public class Agenda {
    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("nome")
    @Expose
    private String nome;
    @SerializedName("telefone")
    @Expose
    private String telefone;
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return nome;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return telefone;
    }
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
}

- InformacoesContato.java
[source,java]
import java.io.Serializable;
public class InformacoesContato implements Serializable {
    private int id;
    private String nome, telefone, email;
    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return nome;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }
   public String getTelefone() {
        return telefone;
    }
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
}

- Professores.java
[source,java]
import java.util.List;
import javax.annotation.processing.Generated;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
@Generated("jsonschema2pojo")
public class Professores {
    @SerializedName("agenda")
    @Expose
    private List<Agenda> agenda;
    @SerializedName("adicionais")
    @Expose
    private List<Adicionais> adicionais;
    public List<Agenda> getAgenda() {
        return agenda;
    }
    public void setAgenda(List<Agenda> agenda) {
        this.agenda = agenda;
    }
    public List<Adicionais> getAdicionais() {
        return adicionais;
    }
    public void setAdicionais(List<Adicionais> adicionais) {
        this.adicionais = adicionais;
    }
}

- Repositorio.java
[source,java]
mport android.os.Handler;
import android.os.Looper;
import com.example.appgsonhttp_01.util.Conexao;
import com.example.appgsonhttp_01.util.Conversao;
import com.google.gson.Gson;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
public class Repositorio {
    private static final String URL = "digite a URL";
    private ExecutorService executor;
    private Handler mainHandler;
    public Repositorio() {
        this.executor = Executors.newSingleThreadExecutor();
        this.mainHandler = new Handler(Looper.getMainLooper());
    }
    public interface Callback {
        void sucesso(List<InformacoesContato> lista);
        void erro(String mensagem);
    }
    private void sucesso(Callback c, List<InformacoesContato> lista) {
        mainHandler.post(new Runnable() {
            @Override
            public void run() {
                c.sucesso(lista);
            }
        });
    }
    private void erro(Callback c, String mensagem) {
        mainHandler.post(new Runnable() {
            @Override
            public void run() {
                c.erro(mensagem);
            }
        });
    }
    public void obterDados(Callback c) {
        executor.execute(new Runnable() {
            @Override
            public void run() {
                //tarefa da thread
                try {
                    Conexao conexao = new Conexao();
                    InputStream inputStream = conexao.obterRespostaHTTP(URL);
                    Conversao conversao = new Conversao();
                    String jsonString = conversao.converter(inputStream);
                    if (jsonString == null || jsonString.isEmpty()) {
                        erro(c, "Erro - Não existe informações disponíveis");
                        return;
                    }
                    Gson gson = new Gson();
                    Professores professores = gson.fromJson(jsonString, Professores.class);
                    List<InformacoesContato> listaContatos = new ArrayList<>();
                    if (professores != null && professores.getAgenda() != null) {
                        for (Agenda ag : professores.getAgenda()) {
                            InformacoesContato contato = new InformacoesContato();
                            contato.setId(ag.getId());
                            contato.setNome(ag.getNome());
                            contato.setTelefone(ag.getTelefone());
                            if (professores.getAdicionais() != null) {
                                for (Adicionais ad : professores.getAdicionais()) {
                                    if (ad.getId().equals(ag.getId())) {
                                        contato.setEmail(ad.getEmail());
                                        break;
                                    }
                                }
                            }
                            listaContatos.add(contato);
                        }
                    }
                    sucesso(c, listaContatos);
                } catch (Exception e) {
                    e.printStackTrace();
                    erro(c, "Erro - Não foi possível realizar o download" + e.getMessage());
                }
            }
        });
    }//
}//class

- MainViewModel.java
[source,java]
import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;
import com.example.appgsonhttp_01.model.InformacoesContato;
import com.example.appgsonhttp_01.model.Repositorio;
import java.util.List;
public class MainViewModel extends ViewModel {
    private final MutableLiveData<List<InformacoesContato>> listaContatos = new MutableLiveData<>();
    private final MutableLiveData<String> mensagemErro = new MutableLiveData<>();
    private final Repositorio repositorio = new Repositorio();
    public LiveData<List<InformacoesContato>> getListaContatos() {
        return listaContatos;
    }
    public LiveData<String> getMensagemErro() {
        return mensagemErro;
    }
    public void carregarDadosDoRepositorio() {
        repositorio.obterDados(new Repositorio.Callback() {
            @Override
            public void sucesso(List<InformacoesContato> lista) {
                listaContatos.setValue(lista);
            }
            @Override
            public void erro(String mensagem) {
                mensagemErro.setValue(mensagem);
            }
        });
    }
}

- RelatorioViewModel.java
[source,java]
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;
public class RelatorioViewModel extends ViewModel {
    private final MutableLiveData<String> nome_professor = new MutableLiveData<>();
    private final MutableLiveData<String> email_professor = new MutableLiveData<>();
    private final MutableLiveData<String> telefone_professor = new MutableLiveData<>();
    public MutableLiveData<String> getNome_professor() {
        return nome_professor;
    }
    public MutableLiveData<String> getEmail_professor() {
        return email_professor;
    }
    public MutableLiveData<String> getTelefone_professor() {
        return telefone_professor;
    }
    public void pegarInformacoes(String nome_p, String email_p, String telefone_p) {
        this.nome_professor.setValue(nome_p);
        this.email_professor.setValue(email_p);
        this.telefone_professor.setValue(telefone_p);
    }
}

- ContatoAdapter.java
[source,java]
import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import androidx.databinding.DataBindingUtil;
import com.example.appgsonhttp_01.R;
import com.example.appgsonhttp_01.databinding.ItemContatoBinding;
import com.example.appgsonhttp_01.model.InformacoesContato;
import java.util.List;
public class ContatoAdapter extends ArrayAdapter<InformacoesContato> {
    public ContatoAdapter(Context context, List<InformacoesContato> contatos) {
        super(context, 0, contatos);
    }
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        ItemContatoBinding binding;
        if (convertView == null) {
            binding = DataBindingUtil.inflate(LayoutInflater.from(getContext()),
                    R.layout.item_contato, parent, false);
            convertView = binding.getRoot();
            convertView.setTag(binding);
        } else {
            binding = (ItemContatoBinding) convertView.getTag();
        }
        InformacoesContato contato = getItem(position);
        if (contato != null) {
            binding.setContato(contato);
            binding.executePendingBindings();
        }
        return convertView;
    }
}

 - RelatorioActivity.java
[source,java]
import android.os.Bundle;
import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import com.example.appgsonhttp_01.R;
import com.example.appgsonhttp_01.viewmodel.RelatorioViewModel;
import com.example.appgsonhttp_01.databinding.ActivityRelatorioBinding;
import androidx.databinding.DataBindingUtil;
import androidx.lifecycle.ViewModelProvider;
public class RelatorioActivity extends AppCompatActivity {
    private ActivityRelatorioBinding binding;
    private RelatorioViewModel viewModel;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_relatorio);
        binding = DataBindingUtil.setContentView(this, R.layout.activity_relatorio);
        binding.setLifecycleOwner(this);
        viewModel = new ViewModelProvider(this).get(RelatorioViewModel.class);
        binding.setViewModel(viewModel);
        String professor_nome = getIntent().getStringExtra("nome");
        String professor_email = getIntent().getStringExtra("email");
        String professor_telefone = getIntent().getStringExtra("telefone");
        viewModel.pegarInformacoes(professor_nome,professor_email,professor_telefone);
    }
}

- MainActivity.java
[source,java]
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;
import androidx.lifecycle.Observer;
import androidx.lifecycle.ViewModelProvider;
import com.example.appgsonhttp_01.viewmodel.MainViewModel;
import com.example.appgsonhttp_01.R;
import com.example.appgsonhttp_01.databinding.ActivityMainBinding;
import com.example.appgsonhttp_01.model.InformacoesContato;
import java.util.ArrayList;
import java.util.List
public class MainActivity extends AppCompatActivity {
    private ActivityMainBinding binding;
    private ContatoAdapter adapter;
    private List<InformacoesContato> lista;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MainViewModel viewModel = new ViewModelProvider(this).get(MainViewModel.class);
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main);
        lista = new ArrayList<>();
        adapter = new ContatoAdapter(this, lista);
        binding.listViewDados.setAdapter(adapter);
        binding.listViewDados.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                InformacoesContato contatoSelecionado = lista.get(position);
                Intent intent = new Intent(MainActivity.this, RelatorioActivity.class);
                intent.putExtra("nome", contatoSelecionado.getNome());
                intent.putExtra("email", contatoSelecionado.getEmail());
                intent.putExtra("telefone", contatoSelecionado.getTelefone());
                startActivity(intent);
            }
        });
        binding.btObterDados.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                viewModel.carregarDadosDoRepositorio();
            }
        });
        viewModel.getListaContatos().observe(this, new Observer<List<InformacoesContato>>() {
            @Override
            public void onChanged(List<InformacoesContato> contatos) {
                lista.clear();
                lista.addAll(contatos);
                adapter.notifyDataSetChanged();
            }
        });
    }
}













