= Permissões

Um aplicativo no sistema Android pode usar alguns recursos disponíveis como: 

- câmera;

- galeria de fotos;

- arquivos;

- localização do dispositivo e outros.

Para alguns recursos é necessário solicitar acesso ao usuário, isto é feito através das permissões. As permissões são declaradas no arquivo 
Android Manifest.xml e algumas são solicitadas em tempo de execução.

Como consta na documentação oficial (Google Developers), existem 3 tipos de permissões:

- permissões em tempo de instalação: "Quando você declara as permissões no momento da instalação, o sistema automaticamente concede-as quando o usuário 
instala o app.";

- permissões de execução: "[...] conhecidas como permissões perigosas [...] você precisa solicitar permissões de execução no app antes de acessar os dados
restritos ou realizar ações restritas." 	

- permissões especiais: "Somente a plataforma e os OEMs podem definir permissões especiais."

Referência do texto entre aspas: GOOGLE DEVELOPERS. Permissões no Android. Disponível em: 
https://developer.android.com/guide/topics/permissions/overview?hl=pt-br>. Acesso em: 23 de fev. 2023.

Permissões no Android

video::zCAx4WZ98rs[youtube, width=640, height=480]

Solicitar permissões

video::x38dYUm7tCY[youtube, width=640, height=480]

Permissões em Tempo de Execução

video::C8lUdPVSzDk[youtube, width=640, height=480]

Exemplos práticos:

- No arquivo AndroidManifest.xml, deve ser acrescentado a tag <uses-permission android:name="android.permission.CAMERA" />.

- link:um/activity_main.xml[activity_main]

- link:um/MainActivity.java[MainActivity]

- link:um/activity_segunda.xml[activity_segunda]

- link:um/SegundaActivity.java[SegundaActivity]

Análise da classe PermissionUtils.java, disponível no seguinte endereço: https://github.com/googlemaps/android-samples/blob/main/ApiDemos/java/app/src/gms/java/com/example/mapdemo/PermissionUtils.java. 


= Google Maps

Com o SDK do Google Maps é possível adicionar mapa em seu projeto, usar recursos de localização, pontos de latitude e longitude, personalização de marcadores e outros.

Para criar um projeto no AndroidStudio usando os recursos do SDK do Google Maps é necessário fazer algumas configurações na IDE e também na Google Cloud.

Para mais informações:

- Visão geral do SDK do Maps para Android. Disponível em: https://developers.google.com/maps/documentation/android-sdk/overview?hl=pt-br&section=tools. Acessado em: 10 fev. 2023.

Passos iniciais: marcadores

video::l3bw8Senjmg[youtube, width=640, height=480]

Personalizações: marcadores

video::FFm9NmSfjw0[youtube, width=640, height=480]

Exemplos práticos (personalizando marcadores):

 - crie um projeto na IDE;

- escolha o Google Maps Activity;

- Na classe MainActivity.java no método OnMapReady faça as seguintes adições:
@Override

    public void onMapReady(GoogleMap googleMap) {

        mMap = googleMap;

        LatLng sydney = new LatLng(-34, 151);

        mMap.addMarker(new MarkerOptions()   //adiciona um marcador

                .position(sydney)                                  //especifica a posição 

                .title("Marker in Sydney")			//define o título no marcador

                .draggable(true)					//torna o marcador arrastável

                .snippet("Hello")					//texto adicional ao marcador

                .icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_GREEN))   //muda a cor do marcador

                .rotation(90.F));   //gira o marcador


        mMap.moveCamera(CameraUpdateFactory.newLatLng(sydney));   

    }

}

Para mais detalhes sobre SDK MAPS:

- GOOGLE DEVELOPERS. Marker. Disponível em: https://developers.google.com/maps/documentation/android-sdk/marker?hl=pt-br. Acesso em: 10 fev. 2023.

- GOOGLE DEVELOPERS. CameraPosition. Disponível em: <https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition. Acessado em: 10 fev. 2023.

- GOOGLE DEVELOPERS. LatLngBounds. Disponível em: https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/LatLngBounds. Acessado em: 10 fev. 2023.

- GOOGLE DEVELOPERS: Location. Disponível em: https://developers.google.com/maps/documentation/android-sdk/location?hl=pt-br. Acesso em: 10 fev. 2023.

Exemplos práticos disponíveis na documentação sobre Google Maps (destacando: limitação de mapa, configurações de zoom, posição da câmera e localização de usuário): 

- GOOGLEMAPS/ANDROID-SAMPLES. Disponível em: https://github.com/googlemaps/android-samples. Acessado em: 10 fev. 2023.
