= Notificações

São mensagens emitidas na tela do dispositivo móvel para informar o usuário sobre downloads, atualizações, eventos, etc. As notificações podem ser emitidos por aplicativos de terceiros instalados, do próprio sistema operacional, mensagens de operadoras, de promoções, chamadas de telefones não atendidas. Conforme consta na documentação oficial (Google Developers), "uma notificação é uma mensagem que o Android exibe fora da interface do seu app para fornecer ao usuário lembretes, comunicações de outras pessoas ou outros informações oportunas do seu app. Os usuários podem tocar na notificação para abrir seu ou realizar uma ação diretamente da notificação".

Referência do texto entre aspas: GOOGLE DEVELOPERS. Visão geral de notificações. Disponível em: https://developer.android.com/develop/ui/views/notifications?hl=pt-br. Acesso em: 03 de out. 2024.

As notificações podem ser simples, expandidas, ter a capacidade de responder ao toque do usuário. Um ponto importante em relação às notificações, 
é que é necessário criar um canal antes de exibi-las.

Exemplos práticos:

- link:um/activity_main.xml[activity_main]

- link:um/MainActivity.java[MainActivity]

Antes de criar e emitir uma notificação, é necessário criar um canal. Conforme Google Developers (2020), "Antes de entregar a notificação no Android 8.0 e versões mais recentes, você precisa registrar o canal de notificação do seu app no sistema, transmitindo uma instância de NotificationChannel para createNotificationChannel()."

- Referência do texto entre aspas: GOOGLE DEVELOPERS. Criar uma notificação. Disponível em: https://developer.android.com/training/notify-user/build-notification?hl=pt-br. Acesso em: 23 de fev. 2023.

Exemplos práticos:

- link:dois/activity_main.xml[activity_main]

- link:dois/MainActivity.java[MainActivity]

- link:dois/activity_segunda.xml[activity_segunda]

- link:dois/SegundaActivity.java[SegundaActivity]

Observe que neste exemplo, a notificação mostra uma mensagem. Quando o usuário clicar na notificação, será chamada uma outra Activity que apresenta a mensagem "Olá". Esta atividade não pertence ao fluxo normal do aplicativo, por isso foi usada a flag Intent.FLAG_ACTIVITY_NEW_TASK ou

Intent.FLAG_ACTIVITY_CLEAR_TASK

Exemplos práticos:

- link:tres/activity_main.xml[activity_main]

- link:tres/MainActivity.java[MainActivity]

Exemplos práticos:

- link:quatro/activity_main.xml[activity_main]

- link:quatro/notification_layout.xml[notification_layout]

- link:quatro/MainActivity.java[MainActivity]

