//caminho padrão para imagens

:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

= Navigation Drawer

O Navigation Drawer é um componente que permite construir um menu lateral que desliza no sentido esquerda para a direita. É possível criar um Navigation Drawer do zero, mas atualmente, é disponibilizado o template pronto do Navigation Drawer quando você cria um projeto no Android Studio. Dessa forma, o trabalho fica compreendido em entender a função de vários elementos que o compõe que pode ser visto logo a seguir nos Exemplos práticos.

Para mais detalhes:

- GOOGLE MATERIAL DESIGN. Navigation Drawer. Disponível em: https://material.io/components/navigation-drawer. Acessado em: 10 fev. 2023.

- Android Developers. Disponível em: https://www.youtube.com/watch?v=DkT0vS14Um0. Acessado em: 10 fev. 2023.

Exemplos práticos (Elementos do Navigation Drawer):

- link:codigos/BiscoitoFragment.java[BiscoitoFragment]
- link:codigos/fragment_biscoito.xml[fragment_biscoito]
- link:codigos/MainActivity.java[MainActivity]
- link:codigos/activity_main.xml[activity_main]
- link:codigos/activitiy_main_drawer.xml[activitiy_main_drawer]
- link:codigos/app_bar_main.xml[app_bar_main]
- link:codigos/content_main.xml[content_main]
- link:codigos/main.xml[main]
- link:codigos/mobile_navigation.xml[mobile_navigation]
- link:codigos/nav_header_main.xml[nav_header_main]

= Animação Usando Arquivos JSON

Já vimos nos tópicos anteriores que o arquivo JSON facilita a troca de dados entre aplicativos, mas seria possível aplicá-lo em outras situações? Por exemplo: em animações? Sim, atualmente o JSON é usado também para essa finalidade, um exemplo disto é a biblioteca Lottie que renderiza animações exportadas do software Adobe After Effects.

Para saber mais detalhes sobre a biblioteca, acesse o projeto disponível no GitHub no seguinte endereço: https://github.com/airbnb/lottie-android

Exemplos práticos:

- Crie um projeto na IDE;

- Escolha uma Activity vazia;

- No arquivo build.gradle, adicione uma dependência:
dependencies 

{

    ...

    implementation "com.airbnb.android:lottie:4.2.2"  //obter a lib

    ...
}

- Clique com o botão direito do mouse na pasta res e adicione um diretório chamado raw. Coloque o arquivo json baixado neste diretório.

- No arquivo activity_main.xml, acrescente a tag:
<com.airbnb.lottie.LottieAnimationView

   android:id="@+id/animation_view"

   android:layout_width="wrap_content"

   android:layout_height="wrap_content"

   app:lottie_rawRes="@raw/cube"    //onde fica o arquivo json

   app:lottie_autoPlay="true"   //iniciar a animação

   app:lottie_loop="true"   //animação continua indefinidamente

   />
   
   - Pronto, basta executar o app.
   
Referências do exemplo acima:

- AIRBNB. Getting Started. Disponível em: https://airbnb.io/lottie/#/android. Acessado em: 10 fev. 2023.
- LOTTIEFILES. Disponível em: https://lottiefiles.com/.Acessado em: 10 fev. 2023.

