= Handler

Permite a troca de mensagens entre a pilha de execução principal e uma pilha de execução secundária. Lembre-se a função da thread principal é redenrizar 
a interface gráfica. Se há a necessidade de fazer uma conexão remota, isto deve ficar a cargo da thread secundária, se um determinado valor presente na 
thread secundária é necessário para atualizar uma view da interface gráfica, o handler pode ser essa ponte entre as duas threads.

Para mais detalhes sobre handler: GOOGLE DEVELOPERS. Handler. Disponível em: https://developer.android.com/reference/android/os/Handler. Acesso em:
24 fev. 2023.

Exemplos práticos (usando POST):

- activity_main.xml
[source,xml]
import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import java.util.Random;
public class MainActivity extends AppCompatActivity {
    private TextView textViewNumber;
    private Button buttonClicar;
    private Handler handler;
    private Integer numberG;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        textViewNumber = findViewById(R.id.textViewNumber);
        buttonClicar = findViewById(R.id.buttonClicar);
    }//onCreate
    public void clicar(View view) {
        switch (view.getId()){
            case R.id.buttonClicar:
                Log.i("Main", String.valueOf(Thread.currentThread()));
                Random random = new Random();
                handler = new Handler();
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        for(int i =0;i<10;i++){
                            Log.i("Thread", String.valueOf(Thread.currentThread()));
                            numberG = random.nextInt(21);
                            try {
                                Thread.sleep(10000);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                            handler.post(new Runnable() {
                                @Override
                                public void run() {
                                    Log.i("Post", String.valueOf(Thread.currentThread()));
                                    textViewNumber.setText(String.valueOf(numberG));
                                }
                            });
                        }//for
                    }
                }).start();
        }//switch
    }//clicar
}//class

- MainActivity.java
[source,java]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:orientation="vertical"
   android:layout_height="match_parent"
   tools:context=".MainActivity">
   <TextView
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:text="Number"
       android:id="@+id/textViewNumber"
        />
   <Button
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:text="CLICK"
       android:onClick="clicar"
       android:id="@+id/buttonClicar"/>
</LinearLayout>

Exemplos práticos (usando MSG):

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".MainActivity">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:id="@+id/textViewNumber"
         />
    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="CLICAR"
        android:onClick="clicar"
        android:id="@+id/buttonClicar"/>
</LinearLayout>

- MainActivity.java
[source,java]
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import java.util.Random;
public class MainActivity extends AppCompatActivity {
    private TextView textViewNumber;
    private Button buttonClicar;
    private Handler handler;
    private Integer numberG;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        textViewNumber = findViewById(R.id.textViewNumber);
        buttonClicar = findViewById(R.id.buttonClicar);
    }//onCreate
    public void clicar(View view) {
        switch (view.getId()){
            case R.id.buttonClicar:
                Log.i("Main",String.valueOf(Thread.currentThread()));
                handler = new MyHandler();
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        Random random = new Random();
                        for(int i =0;i<10;i++){
                            Log.i("Thread",String.valueOf(Thread.currentThread()));
                            int num = random.nextInt(21);
                            try {
                                Thread.sleep(10000);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                            Message msg = new Message();
                            msg.arg1 = num;
                            handler.sendMessage(msg);
                        }//for
                    }
                }).start();
        }//switch
    }//clicar
    private class MyHandler extends Handler{
        @Override
        public void handleMessage(@NonNull Message msg) {
            super.handleMessage(msg);
            textViewNumber.setText(String.valueOf(msg.arg1));
            Log.i("Msg",String.valueOf(Thread.currentThread()));
        }//
    }//inner class
}//class




