//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Padrão MVVM

Trata-se de um padrão de projeto de arquitetura, as camadas são divididas em Model, View e View-Model.

Model: Responsável pela manipulação dos dados. Nesta parte compreendem as classes que representam as entidades e que realizam as persistências no banco de dados.

View: Parte visual do projeto. A View relaciona-se com o ViewModel e não conhece diretamente o Model.

ViewModel: Camada intermediária entre a View e o Model. O ViewModel pode ter acesso ao Model diretamente. O ViewModel atualiza o objeto LiveData através da atualização do Model. O LiveData usa o método observe para atualizar a View. 

Para mais detalhes sobre MVVM acesse o material: SOUTO, Thiago. Arquiteturas em Android: MVVM + Kotlin + Android Architecture Components (Databinding, Lifecycle, LiveData, Room). 2019. Disponível em: <https://medium.com/android-dev-br/arquiteturas-em-android-mvvm-kotlin-android-architecture-components-databinding-lifecycle-d5e7a9023cf3>.

Responsabilidades de alguns componentes dentro do MVVM:

- DataBinding: permite o vínculo da View (por exemplo, um TextView) com um ViewModel. O vínculo é feito de forma declarativa no XML.
- LiveData: é um container que pode ser observado. Isso significa que os componentes da UI (como Activities e Fragments) podem se inscrever para receber atualizações sobre mudanças nos dados. Notifica apenas os observadores que estão em um estado ativo.

O MVVM garante que a interface do usuário seja sempre atualizada de acordo com o ciclo de vida do componente.

Exemplo prático:

Inicialmente no projeto criado habilite o DataBinding, no arquivo gradle a nível de app, acrescente as seguintes linhas:
[source,xml]
android{ ... 
   buildFeatures {
        dataBinding = true
    }
}

- activity_main.xml
[source,xml]
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">  
    <data>
        <variable
            name="viewModel"
            type="com.example.exemplomvvm_01.controller.AlunoViewModel" />
    </data>
    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:items="@{viewModel.alunos}"
            />
    </LinearLayout>
</layout>

- item_aluno.xml
[source,xml]
<layout xmlns:android="http://schemas.android.com/apk/res/android">
    <data>
        <variable
            name="aluno"
            type="com.example.exemplomvvm_01.model.Aluno" />
    </data>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:padding="16dp">
        <TextView
            android:id="@+id/text_nome"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@{aluno.nome}" />
        <TextView
            android:id="@+id/text_nota"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@{String.valueOf(aluno.nota)}"
            android:layout_marginStart="16dp"/>
    </LinearLayout>
</layout>

- MainActivity.java (View)
[source,java]
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;
import androidx.recyclerview.widget.LinearLayoutManager;
import com.example.exemplomvvm_01.controller.AlunoAdapter;
import com.example.exemplomvvm_01.controller.AlunoViewModel;
import com.example.exemplomvvm_01.databinding.ActivityMainBinding;
public class MainActivity extends AppCompatActivity {
    private ActivityMainBinding binding;
    private AlunoViewModel viewModel;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityMainBinding.inflate(getLayoutInflater()); //infla o layout da activity
        setContentView(binding.getRoot()); //define o conteúdo da activity
        viewModel = new ViewModelProvider(this).get(AlunoViewModel.class); //obtém um objeto ViewModel
        binding.setViewModel(viewModel); // permite que o layout tenha acesso direto às propriedades e métodos do ViewModel.
        binding.setLifecycleOwner(this); //binding pode observar as mudanças de estado do ciclo de vida da atividade.
        binding.recyclerView.setLayoutManager(new LinearLayoutManager(this)); //define o layout para o recyclerView
        viewModel.getAlunos().observe(this, alunos -> {
            AlunoAdapter adapter = new AlunoAdapter(alunos);
            binding.recyclerView.setAdapter(adapter);
        });
    }
}

- Aluno.java (Model)
[source,java]
public class Aluno {
    private String nome;
    private int nota;
    public Aluno(String nome, int nota) {
        this.nome = nome;
        this.nota = nota;
    }
    public String getNome() {
        return nome;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getNota() {
        return nota;
    }
    public void setNota(int nota) {
        this.nota = nota;
    }
}

- AlunoRepositorio.java (Model)
[source,java]
import java.util.ArrayList;
import java.util.List;
public class AlunoRepositorio {
    public List<Aluno> obterDadosAlunos(){
        List<Aluno> listaAlunos = new ArrayList<>();
        listaAlunos.add(new Aluno("Ana", 6));
        listaAlunos.add(new Aluno("Rodrigo", 8));
        listaAlunos.add(new Aluno("Paulo", 7));
        return listaAlunos;
    }
}

- AlunoAdapter.java (Controller)
[source,java]
import android.view.LayoutInflater;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;
import com.example.exemplomvvm_01.databinding.ItemAlunoBinding;
import com.example.exemplomvvm_01.model.Aluno;
import java.util.List;
public class AlunoAdapter extends RecyclerView.Adapter<AlunoAdapter.AlunoViewHolder> {
    private List<Aluno> alunos;
    public AlunoAdapter(List<Aluno> alunos) {
        this.alunos = alunos;
    }
    @NonNull
    @Override
    public AlunoViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        ItemAlunoBinding binding = ItemAlunoBinding.inflate(LayoutInflater.from(parent.getContext()), 
        parent, false); //infla o layout
        return new AlunoViewHolder(binding); //retorna a view do item da lista
    }
    @Override
    public void onBindViewHolder(@NonNull AlunoViewHolder holder, int position) {
        holder.bind(alunos.get(position));
    }
    @Override
    public int getItemCount() {
        return alunos.size();
    }
    public void updateAlunos(List<Aluno> novosAlunos) {
        alunos.clear();
        alunos.addAll(novosAlunos);
        notifyDataSetChanged(); 
    }
    public static class AlunoViewHolder extends RecyclerView.ViewHolder {
        private final ItemAlunoBinding binding;
        public AlunoViewHolder(@NonNull ItemAlunoBinding binding) {
            super(binding.getRoot());
            this.binding = binding;
        }
        public void bind(Aluno aluno) {
            binding.setAluno(aluno);//Define o objeto Aluno no binding, permitindo que os dados sejam exibidos na UI.
            binding.executePendingBindings();
//solicita que o DataBinding execute qualquer atualização pendente imediatamente, garantindo que a UI reflita os dados mais recentes.
        }
    }
}

- AlunoViewModel.java (Controller)
[source,java]
import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;
import com.example.exemplomvvm_01.model.Aluno;
import com.example.exemplomvvm_01.model.AlunoRepositorio;
import java.util.ArrayList;
import java.util.List;
public class AlunoViewModel extends ViewModel {
    private final MutableLiveData<List<Aluno>> alunos;
    private AlunoRepositorio alunoRepositorio;
    public AlunoViewModel() {
        alunos = new MutableLiveData<>();
        alunoRepositorio = new AlunoRepositorio();
        alunos.setValue(alunoRepositorio.obterDadosAlunos());
    }
    public LiveData<List<Aluno>> getAlunos() {
        return alunos;
    }
}

- BindingAdapters.java (Controller)
[source,java]
import androidx.databinding.BindingAdapter;
import androidx.recyclerview.widget.RecyclerView;
import com.example.exemplomvvm_01.model.Aluno;
import java.util.List;
public class BindingAdapters {
    @BindingAdapter("items")
    public static void setItems(RecyclerView recyclerView, List<Aluno> alunos) {
        AlunoAdapter adapter = (AlunoAdapter) recyclerView.getAdapter();
        if (adapter != null) {
            adapter.updateAlunos(alunos);
        }
    }
}


   












