//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Padrão MVVM

Trata-se de um padrão de projeto de arquitetura, as camadas são divididas em Model, View e View-Model.

Model: Responsável pela manipulação dos dados. Nesta parte compreendem as classes que representam as entidades e que realizam as persistências.
View: Parte visual do projeto. A View relaciona-se com o ViewModel através do DataBinding e não conhece diretamente o Model.
ViewModel: Camada intermediária entre a View e o Model. Não acessa a View diretamente, para isto é usado o DataBinding. O ViewModel pode ter acesso ao Model diretamente. O ViewModel pode usar um objeto LiveData (observadores) para acompanhar as mudanças nos dados do Model, dessa forma notificando a View quando algo mudou. Lembre-se que a atualização da View através do ViewModel é possível através do DataBinding. 

Para mais detalhes sobre MVVM acesse o material: SOUTO, Thiago. Arquiteturas em Android: MVVM + Kotlin + Android Architecture Components (Databinding, Lifecycle, LiveData, Room). 2019. Disponível em: <https://medium.com/android-dev-br/arquiteturas-em-android-mvvm-kotlin-android-architecture-components-databinding-lifecycle-d5e7a9023cf3>.

Responsabilidades de alguns componentes dentro do MVVM:

- DataBinding: permite o vínculo da View (por exemplo, um TextView) com um ViewModel. Dessa forma, as Views serão atualizadas dinamicamente sem a necessidade de atualização manual.
- ViewModel: sua função é fornecer os dados para a View. Geralmente tem acesso ao Model. Usa o LiveData para observar o Model (em relação ãs mudanças) e notifica a View (através do DataBinding).
- LiveData: classe que possui um observador e também acompanha o ciclo de vida da Activity ou Fragment. O LiveData gera uma notificação quando o Model foi alterado, porém esta notificação só é validada quando a View está ativa.




   












