= Broadcast Receiver

Segundo a Google Developers (2019), "Os apps para Android podem enviar ou receber mensagens de transmissão do sistema Android e de outros apps Android". 
Para entender com mais facilidade os broadcasts, relembre os tratamentos de eventos presentes na linguagem Java. Evento é algo que acontece no sistema:
pode ser sua reinicialização; o aparelho habilitado em modo avião; a bateria sendo carregada, a desabilitação da Wi-fi e assim por diante.
Resumindo: algo acontece, uma classe transmite uma mensagem e outra ficará responsável em tratá-la.

Ainda, de acordo com a  Google Developers (2019), "Os apps podem se registrar para receber transmissões específicas. Quando uma transmissão é enviada,
o sistema a direciona automaticamente para apps que se inscreveram para receber esse tipo específico de transmissão."

Para ocorrer a transmissão da mensagem, é necessário vinculá-la ao um objeto Intent. Através do método setAction é definido o evento que aconteceu. 
Por meio do método putExtra é possível passar mais dados na transmissão da mensagem.

Referência do texto entre aspas: GOOGLE DEVELOPERS. Visão geral de transmissões.Disponível em: 
https://developer.android.com/guide/components/broadcasts#java. Acesso em: 22 de fev. 2023. 

Broadcast Receiver

video::XXVsL3njoCQ[youtube, width=640, height=480]

Existem duas maneiras de definir um BroadcastReceiver:

- No arquivo AndroidManifest.xml;

- Pelo contexto, cuja definição é feita por linha de código dentro de uma classe específica.

Para saber mais sobre as ações de transmissões existentes no Android, acesse na sua máquina a pasta do SDK. Por exemplo, na minha máquina o acesso ao 
arquivo foi: Sdk/platforms/android-31/data/broadcast_actions.txt. 



